# Generated by Django 2.1.7 on 2019-03-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_member',
            field=models.BooleanField(default=False),
        ),
    ]
